### ISSUE TITLE
dist folder

### ISSUE THREAD

**Issue by aminroosta** [binary-com/binary-live-api#1]
Hi boris,

I have tried to build this library.
```
cd binary-live-api && npm install && webpack
```
but **webpack** doesn't seem to recognize the **webpack.config.js** file.

Can you add the prebuild version (**dist** folder) ?
That way when we install it with bower we don't need to build it with webpack.
Thanks.

**Comment by aminroosta** [comment]
@borisyankov 
I was able to build this lib by adding `output.path` and `output.filename` i saw that you had a dist folder in the `.gitignore`, I send a PR https://github.com/binary-com/binary-live-api/pull/2 anyways.

Thanks boris.

**Comment by aminroosta** [comment]
@borisyankov  i get an empty object `{}` when **require**ing the `binary-live-api` with `requirejs`.
Any Idea?

**Comment by aminroosta** [comment]
@borisyankov  i couldn't find out what the problem is. 
I tried compiling with `libararyTarget: "amd"` option but `return __webpack_require__(0);` still returns an empty object.

**Comment by borisyankov** [comment]
The issue is certainly that requirejs uses 'amd' and it is 'umd' which itself is compatible with es6 import.
You should very strongly consider migrating the project to es6 instead of continuing with requirejs. :)

**Comment by aminroosta** [comment]
@borisyankov can't argee anymore. but i think arnab wants to make a release with the current changes we have made, before adding babeljs support, removing bower_components, etc ...

its there a workaround for me to use the current version of `binary-live-api` with requirejs ?

i am not an expert on es6 modules, the reason we use **requirejs** is to load dependencies on demand and improve page load time. i think aranb doesn't want to load everything at once.
that will be huge **bundle.js** file.
I think webpack(or grunt) and bablejs support not support this(right?) and if that's the case i think we have to keep using **requriejs**.

Thanks again.

**Comment by aminroosta** [comment]
@borisyankov  it seems **requirejs** works fine with **es6-modules** compiled vie **umd** option in **webpack**.

the problem was not adding **index.js** file to **entery:** option
```
    entry: [
        'babel/polyfill',
        './src/index'
    ],
```
I have sent another PR https://github.com/binary-com/binary-live-api/pull/3

**Comment by arnabk** [comment]
@borisyankov @aminroosta webtrader code has become giant and it is growing faster. I do plan to move to ES6 with webpack, but I believe that needs to be done after proper planning. We have a deadline to meet to release webtrader because it is pretty much replace everything other charting softwares from binary.com(except tradingview) and giving clients another option to do charting and trading on same page. 
Considering the fact that we are just getting started to know more about webpack and ES6, it should not be a hurried effort, rather a planned approach.

Also as I mentioned earlier, for a library to be popular, it should not be tied to a specific tech. It should support everything because you cannot force a user to use what you want, but you want to help them, just like out WS API which can be called from any tech. So, I think this project supporting all possible way, is a good future for this project for its adaptability.

**Comment by borisyankov** [comment]
@arnabk What is the deadline?

**Comment by arnabk** [comment]
@borisyankov There is no hard cut off date deadline. But every month I get an email from JY asking about progress. That is an indication of soft deadline. Be assured, we will move to webpack. Technology without no customers appreciating the work is useless and customers do not understand tech. They like the app if it works smoothly even if it is coded in BASIC language.
