### ISSUE TITLE
More explanation needed on how to use in Browser

### ISSUE THREAD

**Issue by arnabk** [binary-com/binary-live-api#5]
I think more explanation is needed on how to use this library in browser. We have to be very flexible with libraries because libraries are not just meant for us(only), its for everybody who probably don't have much JS knowledge.

For example
<code>
Usage in the Browser

var api = new LiveApi();
api.authorize('yourtoken');
api.getPortfolio();
api.events.on('portfolio', function(data) {
    // do stuff with portfolio data
});
</code>

I was assuming that, if I start a new simple HTML, JS project and I do npm install binary-live-api and then include the minified version of the js file from dist folder in my index.html, I can do new LiveApi() and start working with the API without getting into too much of the AMD world. But it failed and I was getting "Uncaught ReferenceError: LiveApi is not defined"

**Comment by borisyankov** [comment]
Since this is UMD, it can be consumed by AMD or CommonJs or ES6's import.
It is not available as a global variable though (the thing that modules try to solve)

It can be used as a global in the browser like this:

var LiveApi = require('LiveApi');
if you include this 1K script:
http://stuk.github.io/require1k/
